# Generated by Django 3.1.2 on 2020-11-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='uuid',
            new_name='uid',
        ),
    ]
